[versions]
agp = "8.7.3"
kotlin = "2.1.0"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.8.7"
activityCompose = "1.9.3"
composeBom = "2024.12.01"

jetbrainsKotlinJvm = "2.1.0"

coroutines = "1.9.0"

desugar_jdk_libs = "2.1.3"
kotlinxSerialization = "1.7.3"
gson = "2.11.0"

dagger = "2.51.1"
hiltCompiler = "2.51.1"
hilt = "1.2.0"

okhttp = "4.4.1"
navigation = "2.8.5"
room = "2.6.1"
splashScreen = "1.0.1"
datastorePreferences = "1.1.1"
paging = "3.3.5"
foundation = "1.7.6"

credentials = "1.3.0"
googleId = "1.1.1"

coilCompose = "2.6.0"
material3WindowSizeClass = "1.3.1"
media3 = "1.5.0"
media = "1.7.0"
legacySupport = "1.0.0"
glide = "4.15.1"
secretsPlugin = "2.0.1"
palette = "1.0.0"
work = "2.10.0"

composeCompiler = "1.5.15"

#gradle
androidTools = "31.7.3"
ksp = "2.1.0-1.0.29"

# Project versions
projectApplicationId = "com.poulastaa.kyoku"
projectVersionName = "1.0"
projectMinSdkVersion = "26"
projectTargetSdkVersion = "35"
projectCompileSdkVersion = "35"
projectVersionCode = "1"

appcompat = "1.7.0"
material = "1.12.0"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }

androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }

androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleRuntimeKtx" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

dagger-hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "dagger" }
dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hiltCompiler" }
hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt" }
hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hilt" }

okhttp-url-connection = { group = "com.squareup.okhttp3", name = "okhttp-urlconnection", version.ref = "okhttp" }

navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }

room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

core-splash-screen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashScreen" }

datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastorePreferences" }

pagingRuntimeKtx = { group = "androidx.paging", name = "paging-runtime-ktx", version.ref = "paging" }
pagingCompose = { group = "androidx.paging", name = "paging-compose", version.ref = "paging" }
pagingCommon = { group = "androidx.paging", name = "paging-common", version.ref = "paging" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }

credentials = { group = "androidx.credentials", name = "credentials", version.ref = "credentials" }
credentialsPlayServicesAuth = { group = "androidx.credentials", name = "credentials-play-services-auth", version.ref = "credentials" }
google-id = { group = "com.google.android.libraries.identity.googleid", name = "googleid", version.ref = "googleId" }

coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coilCompose" }

material3WindowSizeClass = { group = "androidx.compose.material3", name = "material3-window-size-class", version.ref = "material3WindowSizeClass" }

media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }
media3-exoplayer-hls = { group = "androidx.media3", name = "media3-exoplayer-hls", version.ref = "media3" }
media3-common = { group = "androidx.media3", name = "media3-common", version.ref = "media3" }
media3-session = { group = "androidx.media3", name = "media3-session", version.ref = "media3" }
media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3" }
media = { group = "androidx.media", name = "media", version.ref = "media" }
legacy-support-V4 = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "legacySupport" }

glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }

androidx-palette = { group = "androidx.palette", name = "palette-ktx", version.ref = "palette" }

# Gradle
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "androidTools" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
room-gradlePlugin = { group = "androidx.room", name = "room-gradle-plugin", version.ref = "room" }

androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }

ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "room" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
secrets-gradle-plugin = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "secretsPlugin" }

kyoku-android-application = { id = "kyoku.android.application", version = "unspecified" }
kyoku-android-application-compose = { id = "kyoku.android.application.compose", version = "unspecified" }
kyoku-android-library = { id = "kyoku.android.library", version = "unspecified" }
kyoku-android-library-compose = { id = "kyoku.android.library.compose", version = "unspecified" }
kyoku-android-feature-ui = { id = "kyoku.android.feature.ui", version = "unspecified" }
kyoku-android-room = { id = "kyoku.android.room", version = "unspecified" }
kyoku-android-dagger = { id = "kyoku.android.dagger", version = "unspecified" }
kyoku-jvm-library = { id = "kyoku.jvm.library", version = "unspecified" }
kyoku-okhttp-library = { id = "kyoku.okhttp.library", version = "unspecified" }

[bundles]
compose = [
    "androidx-activity-compose",
    "androidx-lifecycle-runtime-compose",
    "androidx-lifecycle-viewmodel-compose",
    "androidx-material3",
    "androidx-ui-graphics",
    "androidx-ui-tooling-preview"
]

compose-debug = [
    "androidx-ui-tooling",
    "androidx-ui-test-manifest"
]

media3 = [
    "media3-exoplayer",
    "media3-exoplayer-hls",
    "media3-common",
    "media3-session",
    "media",
    "legacy-support-V4"
]