services:
  mysql-kyoku-user:
    image: mysql:8.4.0
    container_name: mysql-kyoku-user
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_USER_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/init_user.sql:/docker-entrypoint-initdb.d/init_user.sql
      - ./mysql-kyoku-user-data/data:/var/lib/mysql

  mysql-kyoku:
    image: mysql:8.4.0
    container_name: mysql-kyoku
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3308:3306"
    volumes: # sequence in file name is important
      - ./mysql/init_kyoku.sql:/docker-entrypoint-initdb.d/init_kyoku.sql

      - ./mysql/insert/01_EntryAlbum.sql:/docker-entrypoint-initdb.d/01_EntryAlbum.sql
      - ./mysql/insert/02_EntryArtist.sql:/docker-entrypoint-initdb.d/02_EntryArtist.sql
      - ./mysql/insert/03_EntryCountry.sql:/docker-entrypoint-initdb.d/03_EntryCountry.sql
      - ./mysql/insert/04_EntryGenre.sql:/docker-entrypoint-initdb.d/04_EntryGenre.sql
      - ./mysql/insert/05_EntrySong.sql:/docker-entrypoint-initdb.d/05_EntrySong.sql
      - ./mysql/insert/06_EntrySongInfo.sql:/docker-entrypoint-initdb.d/06_EntrySongInfo.sql

      - ./mysql/insert/EntryRelationArtistAlbum.sql:/docker-entrypoint-initdb.d/EntryRelationArtistAlbum.sql
      - ./mysql/insert/EntryRelationArtistCountry.sql:/docker-entrypoint-initdb.d/EntryRelationArtistCountry.sql
      - ./mysql/insert/EntryRelationArtistGenre.sql:/docker-entrypoint-initdb.d/EntryRelationArtistGenre.sql
      - ./mysql/insert/EntryRelationSongAlbum.sql:/docker-entrypoint-initdb.d/EntryRelationSongAlbum.sql
      - ./mysql/insert/EntryRelationSongArtist.sql:/docker-entrypoint-initdb.d/EntryRelationSongArtist.sql
      - ./mysql/insert/EntryRelationSongGenre.sql:/docker-entrypoint-initdb.d/EntryRelationSongGenre.sql

      - ./mysql-kyoku-data/data:/var/lib/mysql

  mysql-artist-shard:
    image: mysql:8.4.0
    container_name: mysql-genre-artist-shard
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3309:3306"
    volumes:
      - ./mysql/init_shard_genre_artist.sql:/docker-entrypoint-initdb.d/init_shard_genre_artist.sql
      - ./mysql-kyoku-shard-genre-artist-data/data:/var/lib/mysql

  redis-kyoku:
    image: redis/redis-stack:latest
    container_name: redis-kyoku
    restart: always
    ports:
      - "6380:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: [
      "redis-server",
      "--requirepass",
      "${REDIS_PASSWORD}",
      "--appendonly",
      "yes"
    ]
    volumes:
      - "./redis-data/data:/data"
