server:
  port: 8000

spring:
  application:
    name: discovery

  profiles:
    active: dev

  config:
    name: config-server
    import: optional:configserver:http://kyoku.poulastaa.shop:1200

  cloud:
    config:
      uri: http://kyoku.poulastaa.shop:1200
      username: admin
      password: configServer101$@

      profile: dev
      label: main
      fail-fast: true

      retry:
        initial-interval: 1000
        multiplier: 1.1
        max-attempts: 6
        max-interval: 2000

      request-connect-timeout: 5000
      request-read-timeout: 5000
  devtools:
    livereload:
      enabled: on
      port: 8001

  cache:
    type: caffeine
    caffeine:
      spec: initialCapacity=50,maximumSize=1000,expireAfterWrite=5s
  output:
    ansi:
      enabled: ${log.ansi:detect}

logging:
  pattern:
    console: "%clr(%5p){level-color}: %msg%n"
  level:
    root: ${log.level:info}


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${eureka.uri:http://kyoku.poulastaa.shop:8000/eureka/}

debug: ${debug:true}